### PR TITLE
Rcl ue foxy refactor, checked tests

### PR DESCRIPTION
**Pull request by vilkun**
removed defaultengine.ini from ignored
fixed little issue with 'grep' (none was inside results)

### CODE REVIEW

**Comment by Tadinu** [comment]
`DefaultEngine.ini` as noted in .gitignore is auto-generated from DefaultEngineBase.ini upon each run as done [here](https://github.com/rapyuta-robotics/turtlebot3-UE/blob/devel/run_editor.sh#L15), thus please don't add it to the repo.

**Comment by Tadinu** [comment]
`DefaultEngine.ini` as noted in [.gitignore](https://github.com/rapyuta-robotics/turtlebot3-UE/blob/SkeletalRobotImporter/.gitignore#L72) is auto-generated from DefaultEngineBase.ini upon each run as done [here](https://github.com/rapyuta-robotics/turtlebot3-UE/blob/devel/run_editor.sh#L15) or [here](https://github.com/rapyuta-robotics/turtlebot3-UE/blob/SkeletalRobotImporter/ExternalTest/run_local_sim_tb3_tests.sh#L60), thus please don't add it to the repo.

**Comment by Tadinu** [comment]
@vilkun 
* `DefaultEngine.ini` as noted in [.gitignore](https://github.com/rapyuta-robotics/turtlebot3-UE/blob/SkeletalRobotImporter/.gitignore#L72) is auto-generated from DefaultEngineBase.ini upon each run as done [here](https://github.com/rapyuta-robotics/turtlebot3-UE/blob/devel/run_editor.sh#L15) or [here](https://github.com/rapyuta-robotics/turtlebot3-UE/blob/SkeletalRobotImporter/ExternalTest/run_local_sim_tb3_tests.sh#L60), thus please don't add it to the repo.
* I suppose your PR should be made to `devel` branch since it only deals with removing ros2 libs LD_LIBRARY_PATH setup.

**Comment by vilkun** [comment]
closed this, created other https://github.com/rapyuta-robotics/turtlebot3-UE/pull/28

**Pull request closed without merging**
